# accessLog: {}
log:
  level: WARN
providers:
  docker:
    exposedByDefault: false
    endpoint: 'tcp://dockerproxy:2375'
    network: traefik-servicenet
  file:
    directory: /etc/traefik/dynamic
    watch: true
api:
  dashboard: true # if you don't need the dashboard disable it
entryPoints:
  web:
    address: ':10080' # will be routed to port 80, see docker-compose.yaml
    http:
      redirections:   # redirect entire entrypoint to https
        entryPoint:
          to: web-secure
          scheme: https      
  web-secure:
    address: ':10443' # will be routed to port 443, see docker-compose.yaml
certificatesResolvers:
  tlschallenge:
    acme:
      # uncomment next line for testing purpose
      # caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      email: hostmaster@example.invalid
      storage: /etc/traefik/acme.json
      tlsChallenge: {}
global:
  sendAnonymousUsage: true # set to false, if you don't want to send anonymous usage data
